// Generated by `supabase gen types typescript --schema public`. Do not edit by hand.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      audit_log: {
        Row: {
          action: string;
          actor_id: string | null;
          actor_role: string;
          created_at: string;
          entity_id: string | null;
          entity_type: string;
          id: string;
          metadata: NonNullable<Json>;
        };
        Insert: {
          action: string;
          actor_id?: string | null;
          actor_role: string;
          created_at?: string;
          entity_id?: string | null;
          entity_type: string;
          id?: string;
          metadata?: NonNullable<Json>;
        };
        Update: {
          action?: string;
          actor_id?: string | null;
          actor_role?: string;
          created_at?: string;
          entity_id?: string | null;
          entity_type?: string;
          id?: string;
          metadata?: NonNullable<Json>;
        };
        Relationships: [
          {
            foreignKeyName: "audit_log_actor_id_fkey";
            columns: ["actor_id"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
        ];
      };
      categories: {
        Row: {
          created_at: string;
          id: string;
          name: string;
          slug: string;
          sort_order: number;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          name: string;
          slug: string;
          sort_order: number;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          name?: string;
          slug?: string;
          sort_order?: number;
          updated_at?: string;
        };
        Relationships: [];
      };
      contact_categories: {
        Row: {
          category_id: string;
          contact_id: string;
          created_at: string;
        };
        Insert: {
          category_id: string;
          contact_id: string;
          created_at?: string;
        };
        Update: {
          category_id?: string;
          contact_id?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "contact_categories_category_id_fkey";
            columns: ["category_id"];
            isOneToOne: false;
            referencedRelation: "categories";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "contact_categories_contact_id_fkey";
            columns: ["contact_id"];
            isOneToOne: false;
            referencedRelation: "contacts";
            referencedColumns: ["id"];
          },
        ];
      };
      contacts: {
        Row: {
          author_id: string;
          created_at: string;
          details: NonNullable<Json>;
          hidden_at: string | null;
          hidden_by: string | null;
          id: string;
          name: string;
          phone: string | null;
          search_vector: unknown;
          updated_at: string;
          website: string | null;
        };
        Insert: {
          author_id: string;
          created_at?: string;
          details?: NonNullable<Json>;
          hidden_at?: string | null;
          hidden_by?: string | null;
          id?: string;
          name: string;
          phone?: string | null;
          search_vector?: never;
          updated_at?: string;
          website?: string | null;
        };
        Update: {
          author_id?: string;
          created_at?: string;
          details?: NonNullable<Json>;
          hidden_at?: string | null;
          hidden_by?: string | null;
          id?: string;
          name?: string;
          phone?: string | null;
          search_vector?: never;
          updated_at?: string;
          website?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "contacts_author_id_fkey";
            columns: ["author_id"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "contacts_hidden_by_fkey";
            columns: ["hidden_by"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
        ];
      };
      invitations: {
        Row: {
          accepted_at: string | null;
          accepted_by: string | null;
          created_at: string;
          email: string;
          expires_at: string;
          id: string;
          invited_by: string;
          role: Database["public"]["Enums"]["member_role"];
          status: Database["public"]["Enums"]["invitation_status"];
          token: string;
          updated_at: string;
        };
        Insert: {
          accepted_at?: string | null;
          accepted_by?: string | null;
          created_at?: string;
          email: string;
          expires_at?: string;
          id?: string;
          invited_by: string;
          role?: Database["public"]["Enums"]["member_role"];
          status?: Database["public"]["Enums"]["invitation_status"];
          token: string;
          updated_at?: string;
        };
        Update: {
          accepted_at?: string | null;
          accepted_by?: string | null;
          created_at?: string;
          email?: string;
          expires_at?: string;
          id?: string;
          invited_by?: string;
          role?: Database["public"]["Enums"]["member_role"];
          status?: Database["public"]["Enums"]["invitation_status"];
          token?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "invitations_accepted_by_fkey";
            columns: ["accepted_by"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "invitations_invited_by_fkey";
            columns: ["invited_by"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
        ];
      };
      members: {
        Row: {
          avatar_url: string | null;
          created_at: string;
          display_name: string;
          id: string;
          removed_at: string | null;
          role: Database["public"]["Enums"]["member_role"];
          updated_at: string;
        };
        Insert: {
          avatar_url?: string | null;
          created_at?: string;
          display_name: string;
          id: string;
          removed_at?: string | null;
          role?: Database["public"]["Enums"]["member_role"];
          updated_at?: string;
        };
        Update: {
          avatar_url?: string | null;
          created_at?: string;
          display_name?: string;
          id?: string;
          removed_at?: string | null;
          role?: Database["public"]["Enums"]["member_role"];
          updated_at?: string;
        };
        Relationships: [];
      };
      moderation_decisions: {
        Row: {
          admin_id: string;
          created_at: string;
          decision: Database["public"]["Enums"]["moderation_action"];
          id: string;
          note: string | null;
          report_id: string;
        };
        Insert: {
          admin_id: string;
          created_at?: string;
          decision: Database["public"]["Enums"]["moderation_action"];
          id?: string;
          note?: string | null;
          report_id: string;
        };
        Update: {
          admin_id?: string;
          created_at?: string;
          decision?: Database["public"]["Enums"]["moderation_action"];
          id?: string;
          note?: string | null;
          report_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "moderation_decisions_admin_id_fkey";
            columns: ["admin_id"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "moderation_decisions_report_id_fkey";
            columns: ["report_id"];
            isOneToOne: true;
            referencedRelation: "reports";
            referencedColumns: ["id"];
          },
        ];
      };
      price_entries: {
        Row: {
          author_id: string;
          contact_id: string;
          created_at: string;
          hidden_at: string | null;
          hidden_by: string | null;
          id: string;
          price_text: string;
          updated_at: string;
        };
        Insert: {
          author_id: string;
          contact_id: string;
          created_at?: string;
          hidden_at?: string | null;
          hidden_by?: string | null;
          id?: string;
          price_text: string;
          updated_at?: string;
        };
        Update: {
          author_id?: string;
          contact_id?: string;
          created_at?: string;
          hidden_at?: string | null;
          hidden_by?: string | null;
          id?: string;
          price_text?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "price_entries_author_id_fkey";
            columns: ["author_id"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "price_entries_contact_id_fkey";
            columns: ["contact_id"];
            isOneToOne: false;
            referencedRelation: "contacts";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "price_entries_hidden_by_fkey";
            columns: ["hidden_by"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
        ];
      };
      referrals: {
        Row: {
          author_id: string;
          body: string;
          contact_id: string;
          created_at: string;
          hidden_at: string | null;
          hidden_by: string | null;
          id: string;
          referrer_label: string | null;
          updated_at: string;
        };
        Insert: {
          author_id: string;
          body: string;
          contact_id: string;
          created_at?: string;
          hidden_at?: string | null;
          hidden_by?: string | null;
          id?: string;
          referrer_label?: string | null;
          updated_at?: string;
        };
        Update: {
          author_id?: string;
          body?: string;
          contact_id?: string;
          created_at?: string;
          hidden_at?: string | null;
          hidden_by?: string | null;
          id?: string;
          referrer_label?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "referrals_author_id_fkey";
            columns: ["author_id"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "referrals_contact_id_fkey";
            columns: ["contact_id"];
            isOneToOne: false;
            referencedRelation: "contacts";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "referrals_hidden_by_fkey";
            columns: ["hidden_by"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
        ];
      };
      reports: {
        Row: {
          author_id: string;
          created_at: string;
          details: string | null;
          id: string;
          reason: Database["public"]["Enums"]["report_reason"];
          status: Database["public"]["Enums"]["report_status"];
          target_id: string;
          target_type: Database["public"]["Enums"]["report_target"];
          triage_label: Database["public"]["Enums"]["triage_label"] | null;
          triage_reason: string | null;
          updated_at: string;
        };
        Insert: {
          author_id: string;
          created_at?: string;
          details?: string | null;
          id?: string;
          reason: Database["public"]["Enums"]["report_reason"];
          status?: Database["public"]["Enums"]["report_status"];
          target_id: string;
          target_type: Database["public"]["Enums"]["report_target"];
          triage_label?: Database["public"]["Enums"]["triage_label"] | null;
          triage_reason?: string | null;
          updated_at?: string;
        };
        Update: {
          author_id?: string;
          created_at?: string;
          details?: string | null;
          id?: string;
          reason?: Database["public"]["Enums"]["report_reason"];
          status?: Database["public"]["Enums"]["report_status"];
          target_id?: string;
          target_type?: Database["public"]["Enums"]["report_target"];
          triage_label?: Database["public"]["Enums"]["triage_label"] | null;
          triage_reason?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "reports_author_id_fkey";
            columns: ["author_id"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
        ];
      };
      reviews: {
        Row: {
          author_id: string;
          body: string | null;
          contact_id: string;
          created_at: string;
          hidden_at: string | null;
          hidden_by: string | null;
          id: string;
          rating: number | null;
          updated_at: string;
        };
        Insert: {
          author_id: string;
          body?: string | null;
          contact_id: string;
          created_at?: string;
          hidden_at?: string | null;
          hidden_by?: string | null;
          id?: string;
          rating?: number | null;
          updated_at?: string;
        };
        Update: {
          author_id?: string;
          body?: string | null;
          contact_id?: string;
          created_at?: string;
          hidden_at?: string | null;
          hidden_by?: string | null;
          id?: string;
          rating?: number | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "reviews_author_id_fkey";
            columns: ["author_id"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "reviews_contact_id_fkey";
            columns: ["contact_id"];
            isOneToOne: false;
            referencedRelation: "contacts";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "reviews_hidden_by_fkey";
            columns: ["hidden_by"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
        ];
      };
      suggestions: {
        Row: {
          contact_id: string | null;
          created_at: string;
          decision_note: string | null;
          id: string;
          kind: Database["public"]["Enums"]["suggestion_kind"];
          payload: NonNullable<Json>;
          reason: string;
          reviewed_at: string | null;
          reviewed_by: string | null;
          status: Database["public"]["Enums"]["suggestion_status"];
          updated_at: string;
        };
        Insert: {
          contact_id?: string | null;
          created_at?: string;
          decision_note?: string | null;
          id?: string;
          kind: Database["public"]["Enums"]["suggestion_kind"];
          payload?: NonNullable<Json>;
          reason: string;
          reviewed_at?: string | null;
          reviewed_by?: string | null;
          status?: Database["public"]["Enums"]["suggestion_status"];
          updated_at?: string;
        };
        Update: {
          contact_id?: string | null;
          created_at?: string;
          decision_note?: string | null;
          id?: string;
          kind?: Database["public"]["Enums"]["suggestion_kind"];
          payload?: NonNullable<Json>;
          reason?: string;
          reviewed_at?: string | null;
          reviewed_by?: string | null;
          status?: Database["public"]["Enums"]["suggestion_status"];
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "suggestions_contact_id_fkey";
            columns: ["contact_id"];
            isOneToOne: false;
            referencedRelation: "contacts";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "suggestions_reviewed_by_fkey";
            columns: ["reviewed_by"];
            isOneToOne: false;
            referencedRelation: "members";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: {
      contact_rating_summaries: {
        Row: {
          average_rating: number | null;
          contact_id: string | null;
          rating_count: number | null;
          review_count: number | null;
        };
        Relationships: [
          {
            foreignKeyName: "reviews_contact_id_fkey";
            columns: ["contact_id"];
            isOneToOne: false;
            referencedRelation: "contacts";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Functions: {
      accept_invitation: { Args: { display_name: string; invite_token: string }; Returns: string };
      create_contact: {
        Args: {
          category_ids: string[];
          contact_details?: Json;
          contact_name: string;
          contact_phone?: string;
          contact_website?: string;
        };
        Returns: string;
      };
      invitation_preview: {
        Args: { invite_token: string };
        Returns: {
          email: string;
          expires_at: string;
        }[];
      };
      set_contact_categories: {
        Args: { category_ids: string[]; target_contact_id: string };
        Returns: undefined;
      };
    };
    Enums: {
      invitation_status: "pending" | "accepted" | "revoked";
      member_role: "member" | "admin";
      moderation_action: "hide" | "remove" | "dismiss";
      report_reason: "incorrect" | "inappropriate" | "obsolete" | "duplicate" | "other";
      report_status: "open" | "resolved" | "dismissed";
      report_target: "contact" | "referral" | "review" | "price_entry";
      suggestion_kind: "freshness" | "alternative" | "duplicate" | "external_review" | "other";
      suggestion_status: "pending" | "approved" | "rejected";
      triage_label: "likely_fine" | "needs_a_look" | "possible_sensitive_personal_info";
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">;

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] & DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  public: {
    Enums: {
      invitation_status: ["pending", "accepted", "revoked"],
      member_role: ["member", "admin"],
      moderation_action: ["hide", "remove", "dismiss"],
      report_reason: ["incorrect", "inappropriate", "obsolete", "duplicate", "other"],
      report_status: ["open", "resolved", "dismissed"],
      report_target: ["contact", "referral", "review", "price_entry"],
      suggestion_kind: ["freshness", "alternative", "duplicate", "external_review", "other"],
      suggestion_status: ["pending", "approved", "rejected"],
      triage_label: ["likely_fine", "needs_a_look", "possible_sensitive_personal_info"],
    },
  },
} as const;
